versions : 2

sources :
  - name : raw
    schema : gz_raw_data
    description : raw data from Greenweez
    tables : 
    - name : product
      identifier: raw_gz_product
      description : raw data from Greenweez for product
    - name : sales
      identifier : raw_gz_sales
      description : raw data from Greenweez for sales
    - name : ship
      identifier : raw_gz_ship
      description : raw data from Greenweez for ship