versions : 2

sources :
  - name : gz_raw_data
    schema : raw
    description : raw data from Greenweez
    tables : 
      - name : raw_gz_product
        identifier: product
        description : raw data from Greenweez for product
      - name : raw_gz_sales
        identifier : sales
        description : raw data from Greenweez for sales
      - name : raw_gz_ship
        identifier : ship
        description : raw data from Greenweez for ship