versions : 2

sources :
  - name : raw
    schema : gz_raw_data
    description : raw data from Greenweez
    tables : 
    - name : product
      identifier: raw_gz_product
      description : raw data from Greenweez for product
      columns :
        - name : products_id
          description : Primary key of the table
          tests :
            - not_null
            - unique   
    - name : sales
      identifier : raw_gz_sales
      description : raw data from Greenweez for sales
    - name : ship
      identifier : raw_gz_ship
      description : raw data from Greenweez for ship
      columns :
        - name : orders_id
          description : Primary key of the table
          tests : 
            - unique
            - not_null
    - name : adwords
      identifier : raw_gz_adwords
      description : campaign detail from adwords
      columns :
        - name : campaign_key
          description : Campaign key for this provider
        - name : date_date
          description : Date of the campaign
      tests :
        - unique :
            column_name: "(campaign_key || '_' || date_date)"
    - name : bing
      identifier : raw_gz_bing
      description : campaign detail from bing
      columns :
        - name : campaign_key
          description : Campaign key for this provider
        - name : date_date
          description : Date of the campaign
      tests :
        - unique :
            column_name: "(campaign_key || '_' || date_date)"
    - name : criteo
      identifier : raw_gz_criteo
      description : campaign detail from criteo
      columns :
        - name : campaign_key
          description : Campaign key for this provider
        - name : date_date
          description : Date of the campaign
      tests :
        - unique :
            column_name: "(campaign_key || '_' || date_date)"
    - name : facebook
      identifier : raw_gz_facebook 
      description : campaign detail from facebook
      columns :
        - name : campaign_key
          description : Campaign key for this provider
        - name : date_date
          description : Date of the campaign
      tests :
        - unique :
            column_name: "(campaign_key || '_' || date_date)"

